package xerrors

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * error模块通用id
 * +++++++++++++++++++++++++++++++++++++++++++++++++++++++现在是 按照活动的 创建时间排序的，并不是根据 +++++++++++++++++++++++++ */
const (
	SuccessCode           int16 = 0  // 请求成功code
	ResultErrorCode       int16 = -1 // 请求失败通用code
	DBExecErrorCode       int16 = -2 // 请求失败通用code
	InvalidHeader         int16 = -3 // 请求协议失败通用code
	UnAcceptRpc           int16 = -4 // 未受理的协议
	ExistOnlineErrorCode  int16 = -5 // 已存在在线账号
	InternalErrorCode     int16 = -6
	AsyncRespErrorCode    int16 = -99  // 特殊的code, 用于标识异步返回消息
	NetworkDelayErrorCode int16 = -100 // 网络延时过高

	ArgumentErrorCode                 int16 = 106
	BlackListErrorCode                int16 = 107
	MobileInvalidErrorCode            int16 = 108
	SendSmsErrorCode                  int16 = 109
	SmsCodeErrorCode                  int16 = 110
	ThirdpartyErrorCode               int16 = 111
	UserNotExistErrorCode             int16 = 112
	TokenErrorCode                    int16 = 113
	TableInErrorCode                  int16 = 114
	TableNotExistErrorCode            int16 = 115
	TableIdErrorCode                  int16 = 116
	CreateTableErrorCode              int16 = 117
	TableIsFullErrorCode              int16 = 118
	GetGameServerErrorCode            int16 = 119
	IdAuthorErrorCode                 int16 = 120
	InvalidIdErrorCode                int16 = 121
	UserExistErrorCode                int16 = 122
	InvalidPermissionCode             int16 = 123
	InReviewErrorCode                 int16 = 124
	InValidHouseErrorCode             int16 = 125
	InValidHouseMemberErrorCode       int16 = 126
	InValidHouseFloorErrorCode        int16 = 127
	InValidHouseTableErrorCode        int16 = 128
	NotInGameErrorCode                int16 = 129
	InValidHouseTablePlayingErrorCode int16 = 130
	IsFrozenErrorCode                 int16 = 131
	HouseFloorExistErrorCode          int16 = 132
	InValidHouseMemberRoleCode        int16 = 133
	GameBeginCanNotExitCode           int16 = 134
	ServerMaintainErrorCode           int16 = 135
	GameMaintainErrorCode             int16 = 136
	HouseMaxOverFlowCode              int16 = 137
	HouseFloorMaxOverFlowCode         int16 = 138
	HouseMemMaxOverFlowCode           int16 = 139
	HouseMemAdminMaxOverFlowCode      int16 = 140
	HouseTableMaxOverFlowCode         int16 = 141
	MemHouseMaxOverFlowCode           int16 = 142
	NotEnoughCardCode                 int16 = 143
	HouseNotEnoughCardCode            int16 = 144
	HouseFloorRuleChangeCode          int16 = 145
	HouseFloorTableCreating           int16 = 146
	SiteNotExistErrorCode             int16 = 147
	TableInLockErrorCode              int16 = 148
	HouseFloorTableJoining            int16 = 149
	TableInChangeErrorCode            int16 = 150
	HouseFloorNotAliveCode            int16 = 151
	HouseFloorNotSupportCode          int16 = 152
	HouseFloorActivityTimeCode        int16 = 153
	HouseActivityExistCode            int16 = 154
	HouseActivityNotExistCode         int16 = 155
	HouseFloorRuleChangeStrongCode    int16 = 156
	SiteIsFullErrorCode               int16 = 157
	GoldNotEnoughErrorCode            int16 = 158
	GoldExceedingErrorCode            int16 = 159
	TaskNotCompletedCode              int16 = 160
	TaskNotExistCode                  int16 = 161
	ChatErrorCode                     int16 = 162
	TaskRewardedCode                  int16 = 163
	HouseIdOccupyCode                 int16 = 164
	HousePlayOftenNullCode            int16 = 165
	AreaGameNullCode                  int16 = 166
	HouseNoConditionsCode             int16 = 167
	HouseTableFullCode                int16 = 168
	MatchGameNullCode                 int16 = 169
	MatchGameErrCode                  int16 = 170
	MatchAwardNullCode                int16 = 171
	MatchRankingNullCode              int16 = 172
	HouseActMaxOverFlowCode           int16 = 173
	HouseMemAllReadyPartnerCode       int16 = 174
	InValidHousePartnrErrorCode       int16 = 175
	HouseCreatorRefusePartnerCode     int16 = 176
	HouseRefusePartnerCode            int16 = 177
	VitaminNotEnoughErrorCode         int16 = 178
	HouseTableLimitGroupMaxCode       int16 = 179
	HouseTableLimitUserMaxCode        int16 = 180
	HouseTableLimitJoinCode           int16 = 181
	InvalidParamCode                  int16 = 182
	NotAllowHouseVitaminCode          int16 = 183
	ErrorFloorNameCode                int16 = 184
	HouseAlreadyMixCode               int16 = 185
	HouseNotMixCode                   int16 = 186
	InValidLeagueCode                 int16 = 187
	UserInFloorGameCode               int16 = 188
	TableTooManyCode                  int16 = 189
	NoEmptyTableCode                  int16 = 190
	InvalidAreaCode                   int16 = 191
	HouseMemHideCode                  int16 = 192
	LimitGameCode                     int16 = 193
	DelPartnerFirstCode               int16 = 194
	HouseFloorTableFullCode           int16 = 195
	OpenGpsErrorCode                  int16 = 196
	VitaminNotZeroCode                int16 = 197
	VitaminLowerLimitCode             int16 = 198
	VitaminSendNotEnoughCode          int16 = 199
	VitaminPutNotEnoughCode           int16 = 200
	SendSelfVitaminCode               int16 = 201
	UserStatusJoinErrorCode           int16 = 202
	UserStatusExitErrorCode           int16 = 203
	ArgumentTooLargerCode             int16 = 204
	VitaminMainOnErrorCode            int16 = 205
	VitaminGPauseOnErrorCode          int16 = 206
	PartnerGenFailCode                int16 = 207
	InvalidSearchIdCode               int16 = 208
	onlyQucikJoinErrorCode            int16 = 209
	VitaminNotEnougtToZeroErrorCode   int16 = 210
	HouseBusyErrorCode                int16 = 211
	HouseUnFrozenErrorCode            int16 = 212
	HouseDissolveErrorCode            int16 = 213
	HouseMemberExitErrorCode          int16 = 214
	HouseInviteCodeErrorCode          int16 = 215
	UserInGameDescVitaminCode         int16 = 216
	HousePartnerSetVitaminDisableCode int16 = 217
	HouseVitaminNotAbleErrorCode      int16 = 218
	HousePartnerKickVitaminErrorCode  int16 = 219
	HouseCreateVicePartnerErrorCode   int16 = 220
	HouseAdminSetVitaminDisableCode   int16 = 221
	HouseFloorJoinVipErrorCode        int16 = 222
	HouseMemExitApplyErrorCode        int16 = 223
	DailyRewardErrorCode              int16 = 224
	OpenGVoiceErrorCode               int16 = 225
	InitGVoiceErrorCode               int16 = 226
	GoldNotEnoughErrorCode2           int16 = 227 // 金币不足领取低保错误
	AreaGoldGameNullCode              int16 = 228
	GameShareRewardUpperLimit         int16 = 229
	LastGameInfoCode                  int16 = 230 // 牌局已结束，发送最后一局的牌局信息
	LastGameCardsInfoCode             int16 = 231 // 牌局已结束，发送最后一局的牌局信息
	LastGameEndInfoCode               int16 = 232 // 牌局已结束，发送最后一局的牌局信息
	UserPurchasedBankruptGiftCode     int16 = 234 // 牌局已结束，发送最后一局的牌局信息
	TableIsNotSupportLookonErrCode    int16 = 235 // 牌局不支持旁观
	InvalidTimeIntervalErrorCode      int16 = 236 // 无效筛选时段单位
	InvalidTimeRangeErrorCode         int16 = 237 // 无效筛选区间
	NotHaveTaskCode                   int16 = 238 // 没有任务
	TaskTaskStaExceptionCode          int16 = 239 // 任务状态异常
	CouponNotEnoughCode               int16 = 240 // 礼券不足
	ShopProductSoldOutCode            int16 = 241 // 商品库存不足
	ShopProductOffShelfCode           int16 = 242 // 商品已下架
	ShopPhoneNotBindCode              int16 = 243 // 兑换手机尚未绑定
	GoldNotEnoughErrorCode3           int16 = 244 // 小程序金币不足，无法进入房间
	AlarmValueErrorCode               int16 = 245 // 触发警戒值
	PartnerLinkBanErrorCode           int16 = 246 // 全队禁止
	UserAgentNotConfigErrorCode       int16 = 247 // 没有注册盟主后台
	HousePartnerNotEnoughCardCode     int16 = 248
	NoChanceToDo                      int16 = 249
	TodayHasCheckinErrorCode          int16 = 250
	VitaminTooEnoughErrorCode         int16 = 251
)

const (
	ChangeTableError    int16 = 300 // 换桌失败特殊处理
	BlankUserErrorCode  int16 = 301 // 换桌失败特殊处理
	BlankHouseErrorCode int16 = 302 // 换桌失败特殊处理
)
