package xerrors

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * error模块初始化
 * ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
var (
	RespOk                          = newXError(SuccessCode, "操作成功")
	DBExecError                     = newXError(DBExecErrorCode, "数据库操作异常")
	UnAcceptRpcError                = newXError(UnAcceptRpc, "未受理的通讯协议")
	NetworkDelayError               = newXError(NetworkDelayErrorCode, "网络延时过高，为保证您游戏体验正在重新连接.")
	ArgumentError                   = newXError(ArgumentErrorCode, "无效的参数")
	ServerMaintainError             = newXError(ServerMaintainErrorCode, "游戏维护中，请稍后再试.")
	GameMaintainError               = newXError(GameMaintainErrorCode, "游戏维护中，请稍后再试..")
	BlackListError                  = newXError(BlackListErrorCode, "您被禁止登录，请联系客服")
	MobileInvalidError              = newXError(MobileInvalidErrorCode, "手机号不合法")
	SendSmsError                    = newXError(SendSmsErrorCode, "短信验证码发送失败")
	SmsCodeError                    = newXError(SmsCodeErrorCode, "手机号或验证码错误")
	ThirdpartyError                 = newXError(ThirdpartyErrorCode, "第三方服务请求失败")
	UserNotExistError               = newXError(UserNotExistErrorCode, "用户不存在")
	TokenError                      = newXError(TokenErrorCode, "登录已过期，请重新登录")
	TableInError                    = newXError(TableInErrorCode, "加入牌桌失败")
	TableNotExistError              = newXError(TableNotExistErrorCode, "找不到对应房间，请重试")
	TableIdError                    = newXError(TableIdErrorCode, "牌局已结束/解散")
	CreateTableError                = newXError(CreateTableErrorCode, "创建牌桌失败")
	DelTableError                   = newXError(CreateTableErrorCode, "删除牌桌失败")
	TableIsFullError                = newXError(TableIsFullErrorCode, "牌桌已坐满")
	GetGameServerError              = newXError(GetGameServerErrorCode, "游戏维护中...")
	IdAuthorError                   = newXError(IdAuthorErrorCode, "生成识别码失败")
	InvalidIdError                  = newXError(InvalidIdErrorCode, "无效的ID")
	UserExistError                  = newXError(UserExistErrorCode, "用户已存在")
	InvalidPermission               = newXError(InvalidPermissionCode, "权限不足")
	InReviewError                   = newXError(InReviewErrorCode, "等待管理员审核")
	InValidHouseError               = newXError(InValidHouseErrorCode, "包厢不存在")
	InValidHouseMemberError         = newXError(InValidHouseMemberErrorCode, "您不是包厢成员")
	InValidHousePartnerError        = newXError(InValidHousePartnrErrorCode, "无效包厢队长，请重试。")
	InValidHouseFloorError          = newXError(InValidHouseFloorErrorCode, "无效的包厢楼层")
	InValidHouseTableError          = newXError(InValidHouseTableErrorCode, "无效的包厢牌桌")
	NotInGameError                  = newXError(NotInGameErrorCode, "游戏id错误")
	ExistHouseTablePlayingError     = newXError(InValidHouseTablePlayingErrorCode, "存在正在游戏的牌桌")
	IsFrozenError                   = newXError(IsFrozenErrorCode, "本包厢维护中，请联系包厢盟主")
	HouseFloorExistError            = newXError(HouseFloorExistErrorCode, "存在包厢楼层")
	InValidHouseMemberRoleError     = newXError(InValidHouseMemberRoleCode, "无效的用户状态")
	GameBeginCanNotExitError        = newXError(GameBeginCanNotExitCode, "游戏已经开始，无法退出")
	HouseMaxOverFlowError           = newXError(HouseMaxOverFlowCode, "包厢创建数量达到上限")
	HouseFloorMaxOverFlowError      = newXError(HouseFloorMaxOverFlowCode, "包厢楼层数量达到上限")
	HouseMemJoinMaxError            = newXError(HouseMemMaxOverFlowCode, "包厢人数达到上限")
	HouseMemAdminMaxOverFlowError   = newXError(HouseMemAdminMaxOverFlowCode, "包厢管理员人数达到上限")
	HouseTableMaxOverFlowError      = newXError(HouseTableMaxOverFlowCode, "牌桌异常")
	MemJoinHouseMaxError            = newXError(MemHouseMaxOverFlowCode, "加入包厢数量达到上限")
	HouseNotEnoughCardError         = newXError(HouseNotEnoughCardCode, "很抱歉，包厢盟主可用房卡不足，无法进行游戏，请联系盟主充值")
	NotEnoughCardError              = newXError(NotEnoughCardCode, "可用房卡数量不足")
	HouseFloorRuleChangeError       = newXError(HouseFloorRuleChangeCode, "当前包厢规则已修改，暂时未应用于此桌，确定加入游戏吗?")
	HouseFloorTableCreatingError    = newXError(HouseFloorTableCreating, "牌桌正在创建，请稍后再试")
	SiteNotExistError               = newXError(SiteNotExistErrorCode, "游戏房间不存在")
	TableInLockError                = newXError(TableInLockErrorCode, "正在其他房间游戏，加入牌桌失败")
	HouseFloorTableJoiningError     = newXError(HouseFloorTableJoining, "牌桌正在加入，请稍后再试")
	TableInChangeError              = newXError(TableInChangeErrorCode, "游戏中，不能换桌")
	HouseFloorNotAliveError         = newXError(HouseFloorNotAliveCode, "未受理的操作，请稍后再试")
	HouseFloorNotSupportError       = newXError(HouseFloorNotSupportCode, "未支持的操作，请稍后再试")
	HouseFloorActivityTimeError     = newXError(HouseFloorActivityTimeCode, "活动时间有误，请稍后再试")
	HouseActivityExistError         = newXError(HouseActivityExistCode, "存在活动，请删除后重试")
	HouseActivityNotExistError      = newXError(HouseActivityNotExistCode, "活动不存在,请稍后再试")
	HouseFloorRuleChangeStrongError = newXError(HouseFloorRuleChangeStrongCode, "楼层玩法需更新，请盟主点击楼层管理-设置-保存设定完成更新.")
	SiteIsFullError                 = newXError(SiteIsFullErrorCode, "场次人数已满")
	GoldNotEnoughError              = newXError(GoldNotEnoughErrorCode, "您持有的金币不足，无法进入该房间，即刻补充金币，决战到天明吧！")
	GoldExceedingError              = newXError(GoldExceedingErrorCode, "您的金币已超出该房间的最大上限了，请前往高倍场一展身手吧！")
	TaskNotCompletedError           = newXError(TaskNotCompletedCode, "任务未完成")
	TaskNotExistError               = newXError(TaskNotExistCode, "任务不存在")
	TaskStaExceptionError           = newXError(TaskTaskStaExceptionCode, "任务状态异常")
	AsyncRespError                  = newXError(AsyncRespErrorCode, "")
	ChatEerrorCodeError             = newXError(ChatErrorCode, "金币不足，发送失败")
	TaskRewardedError               = newXError(TaskRewardedCode, "已领取奖励")
	HouseIdOccupyError              = newXError(HouseIdOccupyCode, "包厢号码已被占用")
	HousePlayOftenNullError         = newXError(HousePlayOftenNullCode, "无常玩信息")
	AreaGameNullError               = newXError(AreaGameNullCode, "当前地区没有支持的游戏玩法，请尝试切换到其他地区。")
	HouseNoConditionsError          = newXError(HouseNoConditionsCode, "入桌失败")
	HouseTableFullError             = newXError(HouseTableFullCode, "桌子人数已满")
	MatchGameNullError              = newXError(MatchGameNullCode, "当前地区的排位赛没有开启。")
	MatchGameKindError              = newXError(MatchGameErrCode, "此排位赛不在服务器列表中。")
	MatchAwardNullError             = newXError(MatchAwardNullCode, "此排位赛奖励列表没有配置。")
	MatchRankingNullError           = newXError(MatchRankingNullCode, "排位赛的排位信息为空！")
	HouseActMaxOverFlowError        = newXError(HouseActMaxOverFlowCode, "包厢活动创建数量已达上限")
	HouseMemAllReadyPartnerError    = newXError(HouseMemAllReadyPartnerCode, "该玩家非普通成员，禁止调配")
	HouseCreatorRefusePartnerError  = newXError(HouseCreatorRefusePartnerCode, "创建者不能被授权队长")
	HouseRefusePartnerError         = newXError(HouseRefusePartnerCode, "该玩家非普通成员，不能任命或取消")
	VitaminNotEnoughError           = newXError(VitaminNotEnoughErrorCode, "您的比赛金币不足，通过签到、分享、商城充值可获得金币，祝你好运！")
	HouseTableLimitGroupMax         = newXError(HouseTableLimitGroupMaxCode, "您的禁止同桌分组已经到上限")
	HouseTableLimitUserMax          = newXError(HouseTableLimitUserMaxCode, "您的禁止同桌用户数已经到上限")
	HouseTableLimitJoin             = newXError(HouseTableLimitJoinCode, "")
	InvalidParamError               = newXError(InvalidParamCode, "无效的参数")
	NotAllowHouseVitaminError       = newXError(NotAllowHouseVitaminCode, "未开启比赛分功能")
	InvalidFloorNameError           = newXError(ErrorFloorNameCode, "名字不合法")
	HouseAlreadyMixError            = newXError(HouseAlreadyMixCode, "大厅已经开启了混排")
	HouseNotMixError                = newXError(HouseNotMixCode, "该包厢还没有混排大厅")
	InValidLeagueError              = newXError(InValidLeagueCode, "无效的加盟商")
	UserFloorGameError              = newXError(UserInFloorGameCode, "当前楼层有玩家正在游戏,暂无法调整混排模式")
	TableTooManyError               = newXError(TableTooManyCode, "当前桌数已达上限，无法加桌")
	NoEmptyTableError               = newXError(NoEmptyTableCode, "暂时没有空桌子可以删除")
	InvalidAreaCodeError            = newXError(InvalidAreaCode, "无效的区域码")
	NotFrozenError                  = newXError(InvalidAreaCode, "请先冻结包厢")
	HouseMemHideError               = newXError(HouseMemHideCode, "楼主隐藏了成员列表")
	LimitGameError                  = newXError(LimitGameCode, "您暂时不能游戏，请联系盟主或者管理员。")
	DelPartnerFirst                 = newXError(DelPartnerFirstCode, "该玩家已被绑定到其他队长名下，请解除绑定后再尝试")
	HouseFloorTableFullError        = newXError(HouseFloorTableFullCode, "包厢房间过多，暂时不能创建新房间。")
	OpenGpsError                    = newXError(OpenGpsErrorCode, "GPS信号弱")
	VitaminNotZeroError             = newXError(VitaminNotZeroCode, "比赛分为0才可退出包厢，请联系盟主处理")
	VitaminLowerLimitError          = newXError(VitaminLowerLimitCode, "玩家入桌下限不得小于游戏暂停下限。")
	VitaminSendNotEnoughError       = newXError(VitaminSendNotEnoughCode, "您的比赛分配额不足，请先增加自身配额")
	// VitaminPutNotEnoughError            = newXError(VitaminPutNotEnoughCode, "提取的数量不可大于仓库的数量")
	VitaminPutNotEnoughError            = newXError(VitaminPutNotEnoughCode, "超出最大发放分数总额")
	SendSelfVitaminError                = newXError(SendSelfVitaminCode, "不能给自己赠送比赛分")
	ExistOnlineError                    = newXError(ExistOnlineErrorCode, "您已存在在线账号，请稍后重试")
	UserStatusJoinError                 = newXError(UserStatusJoinErrorCode, "正在执行加入牌桌流程，请稍后重试.")
	UserStatusExitError                 = newXError(UserStatusExitErrorCode, "正在执行退出牌桌流程，请稍后重试..")
	VitaminSendPoolError                = newXError(VitaminSendNotEnoughCode, "您的比赛分配额不足，请先增加自身配额")
	ArgumentTooLargerError              = newXError(ArgumentTooLargerCode, "设定数值超出合法范围")
	VitaminMainOnError                  = newXError(VitaminMainOnErrorCode, "请先开启比赛总开关后再进行单玩法赛事配置")
	VitaminGPauseOnError                = newXError(VitaminGPauseOnErrorCode, "请先打开下限暂停总开关后再进行分层设置")
	InvalidSearchIdError                = newXError(InvalidSearchIdCode, "搜索id不正确")
	HouseBusyError                      = newXError(HouseBusyErrorCode, "包厢繁忙中，请稍后重新尝试。")
	HouseUnFrozenError                  = newXError(HouseUnFrozenErrorCode, "请在撤销合并包厢请求后再尝试解冻包厢。")
	OnlyQucikJoinError                  = newXError(onlyQucikJoinErrorCode, "当前包厢设置为仅支持点击“快速入桌”按钮入桌")
	HouseDissolveError                  = newXError(HouseDissolveErrorCode, "合并包厢中不能解散。")
	VitaminNotEnoughToZero              = newXError(VitaminNotEnougtToZeroErrorCode, "比赛分不足，无法清零")
	HouseMemberExitError                = newXError(HouseMemberExitErrorCode, "当前包厢开启了退出包厢审核，请联系盟主处理。")
	HouseInviteCodeError                = newXError(HouseInviteCodeErrorCode, "邀请码不存在，请重新输入。")
	UserInGameDescVitaminError          = newXError(UserInGameDescVitaminCode, "用户/队长正在游戏中，无法扣除比赛分。")
	HousePartnerSetVitaminDisableError  = newXError(HousePartnerSetVitaminDisableCode, "队长/副队长当前无法调整下级比赛分，请联系盟主/管理员处理。")
	VitaminLessZero                     = newXError(HousePartnerSetVitaminDisableCode, "比赛分小于零，无法退出包厢")
	ViAdminMax                          = newXError(HousePartnerSetVitaminDisableCode, "裁判数量到上限了")
	HouseVitaminNotAbleError            = newXError(HouseVitaminNotAbleErrorCode, "需要设置防成谜-比赛分消耗")
	GroupMax                            = newXError(HousePartnerSetVitaminDisableCode, "成员分组到上限了")
	GroupUserMax                        = newXError(HousePartnerSetVitaminDisableCode, "单个分组人数已达上限")
	GroupUserBind                       = newXError(HousePartnerSetVitaminDisableCode, "该玩家已被绑定到其他队长名下，请解除绑定后重试")
	HousePartnerKickVitaminError        = newXError(HousePartnerKickVitaminErrorCode, "移除失败！该玩家比赛分负数大于您的比赛分余额。")
	VicePartnerMaxError                 = newXError(HouseCreateVicePartnerErrorCode, "副队长数量到上限了")
	HouseAdminSetVitaminDisableError    = newXError(HousePartnerSetVitaminDisableCode, "管理员当前无法调整其他玩家比赛分，请联系盟主/管理员处理。")
	HousePartnerSetVitaminDisableError2 = newXError(HousePartnerSetVitaminDisableCode, "队长/副队长当前无法调整名下玩家比赛分，请联系盟主/管理员处理。")
	HouseAllowOneLuckAct                = newXError(HousePartnerSetVitaminDisableCode, "同一时间只能开一个抽奖活动")
	NoLuckTimes                         = newXError(HousePartnerSetVitaminDisableCode, "无抽奖次数")
	HouseFloorJoinVipError              = newXError(HouseFloorJoinVipErrorCode, "您非本玩法vip，无法加入。")
	HouseMemExitApplyError              = newXError(HouseMemExitApplyErrorCode, "无效的退出包厢申请状态，请刷新列表后重试。")
	DailyRewardError                    = newXError(DailyRewardErrorCode, "每日礼包已领取过了")
	OpenGVoiceError                     = newXError(OpenGVoiceErrorCode, "您未开启录音权限。")
	InitGVoiceError                     = newXError(InitGVoiceErrorCode, "实时语音初始化中，请稍后重试。")
	GoldNotEnoughError2                 = newXError(GoldNotEnoughErrorCode2, "您持有的金币不足，无法进入该房间，即刻补充金币，决战到天明吧！！")
	GoldNotEnoughError3                 = newXError(GoldNotEnoughErrorCode3, "当前金币不足，无法进入房间")
	AreaGoldGameNullError               = newXError(AreaGoldGameNullCode, "当前地区没有支持的游戏玩法，请尝试切换到其他地区。")
	GameShareRewardUpperLimitError      = newXError(GameShareRewardUpperLimit, "分享次数已经到达上限,无法领取奖励。")
	LastGameInfo                        = newXError(LastGameInfoCode, "牌局已结束/解散，发送最后一局的牌局信息")
	LastGameCardsInfo                   = newXError(LastGameCardsInfoCode, "牌局已结束/解散，发送最后一局的牌局信息")
	LastGameEndInfo                     = newXError(LastGameEndInfoCode, "牌局已结束/解散，发送最后一局的牌局信息")
	UserPurchasedBankruptGiftError      = newXError(UserPurchasedBankruptGiftCode, "今日已购买破产礼包，不可多次购买。")
	TableIsNotSupportLookonError        = newXError(TableIsNotSupportLookonErrCode, "桌子已满")
	InvalidTimeIntervalError            = newXError(InvalidTimeIntervalErrorCode, "无效筛选时段单位，请核对后重试")
	InvalidTimeRangeError               = newXError(InvalidTimeRangeErrorCode, "无效筛选区间")
	NotHaveTaskError                    = newXError(NotHaveTaskCode, "没有任务或任务已关闭")
	CouponNotEnoughError                = newXError(CouponNotEnoughCode, "礼券不足，无法兑换")
	ShopProductSoldOutError             = newXError(ShopProductSoldOutCode, "商品库存不足")
	ShopProductOffShelfError            = newXError(ShopProductOffShelfCode, "商品已下架")
	ShopPhoneNotBindError               = newXError(ShopPhoneNotBindCode, "兑换手机尚未绑定")
	AlarmValueError                     = newXError(AlarmValueErrorCode, "您的队伍已触发警戒值，请联系队长处理。")
	PartnerLinkBanError                 = newXError(PartnerLinkBanErrorCode, "您的队伍已被禁止游戏，请联系队长处理。")
	UserAgentNotConfigError             = newXError(UserAgentNotConfigErrorCode, "权限错误，包厢盟主未注册团长。")
	HousePartnerNotEnoughCardError      = newXError(HousePartnerNotEnoughCardCode, "很抱歉，你的队长可用房卡不足，无法进行游戏，请联系队长充值")
	NoChanceToDoError                   = newXError(NoChanceToDo, "可用次数不足")
	InternalError                       = newXError(InternalErrorCode, "内部错误")
	CheckinHasError                     = newXError(InternalErrorCode, "今日已签到")
	VitaminTooEnoughError               = newXError(VitaminTooEnoughErrorCode, "您的比赛金币超出上限，去高分场一展身手吧！")
)

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * 自定义Error结构
 * ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
type XError struct {
	Code int16  `json:"code"`
	Msg  string `json:"msg"`
}

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * 实现Error接口
 * ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
func (err *XError) Error() string {
	return err.Msg
}

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * 返回指定错误对象
 * ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
func newXError(code int16, msg string) *XError {
	return &XError{
		Code: code,
		Msg:  msg,
	}
}

/* ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 * 返回自定义错误对象
 * ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */
func NewXError(info string) *XError {
	return newXError(ResultErrorCode, info)
}
